In [44]:
import pandas as pd

In [45]:
df = pd.read_csv("../data/cloud_df.csv")

In [46]:
df = df.sort_values(by="calories", ascending=False)

In [47]:
df = df[df["calories"]<20000]

In [48]:
df.head()

,recipe_id,mean_rating,comment_count,techniques,name,minutes,contributor_id,submitted,n_steps,date,user_id,ingredients_replaced,calories
108889,250949,2.0,2,"['barbecue', 'broil', 'grill', 'smoke']",honey barbecue riblets applebee s,135,399211,2007-09-04,10,"['2012-05-28', '2018-01-12']","[1065980, 2001527511]","['pork riblet', 'barbecue sauce', 'water', 'li...",19382.1
168770,460592,5.0,1,"['bake', 'combine', 'pour', 'toss']",cracker snack mix,50,679953,2011-07-19,4,['2011-08-09'],[424680],"['chip', 'ature pretzel', 'butter cracker', 'w...",18268.7
13517,32152,4.5,4,"['bake', 'boil', 'drain', 'mash', 'melt', 'smo...",potato crumble,40,29956,2002-06-25,9,"['2002-10-28', '2003-07-24', '2005-10-10', '20...","[27813, 82367, 97901, 274977]","['potato', 'butter', 'scallion', 'garlic', 'mi...",18237.8
152095,386564,5.0,2,"['boil', 'pour', 'strain']",homesteader s fireweed honey,60,505521,2009-08-21,6,"['2009-08-24', '2015-07-30']","[527607, 2000373798]","['red clover blossom', 'white clover blossom',...",17554.0
119392,281107,5.0,1,"['bake', 'pour']",chocolate chip snowflake cake,50,463498,2008-01-23,10,['2011-01-26'],[1806667],"['all-purpose flmy', 'sugar', 'baking powder',...",17280.4

In [49]:
df.sort_values(by="minutes", ascending=False)

,recipe_id,mean_rating,comment_count,techniques,name,minutes,contributor_id,submitted,n_steps,date,user_id,ingredients_replaced,calories
103754,236379,2.500000,2,['strain'],apple cinnamon liqueur,129615,327115,2007-06-21,7,"['2013-02-25', '2015-10-16']","[634323, 1802370483]","['granny smith apple', 'cinnamon stick', 'vodk...",4.2
103725,236274,3.000000,1,['strain'],strawberry liqueur,129615,327115,2007-06-21,7,['2009-01-05'],[92006],"['strawberry', 'vodka', 'sugar', 'water', 'gly...",4.2
3821,13264,4.684211,19,"['boil', 'combine', 'freez', 'strain', 'thicken']",limoncello lemoncella,115230,14749,2001-10-25,11,"['2002-01-07', '2002-11-21', '2003-01-20', '20...","[28242, 19419, 64032, 27526, 47559, 160743, 97...","['lemon', '100 proof vodka', 'sugar', 'water']",2482.9
75679,165697,0.000000,1,"['combine', 'strain']",dandelion wine,87842,26657,2006-04-25,6,['2006-04-26'],[233194],"['dandelion flower', 'hot water', 'lemon, juic...",7235.9
45872,98818,3.750000,4,"['crush', 'drain', 'pickle']",joanne s sweet and hot pickles,86407,54978,2004-08-31,8,"['2014-05-05', '2007-09-11', '2011-09-15', '20...","[37449, 269594, 815814, 868202]","['pickle', 'sugar', 'tabasco sauce', 'garlic']",1649.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
167329,455593,4.666667,3,"['blend', 'puree', 'refrigerat', 'smooth']",good stuff sauce by top chef spike mendelsohn,1,841835,2011-05-09,3,"['2011-05-20', '2013-10-20', '2013-10-30']","[1867993, 37449, 383346]","['mayonnaise', 'ketchup', 'molass', 'rice vine...",61.8
132899,320671,4.833333,6,['strain'],lemon drop shot,1,209747,2008-08-21,5,"['2008-08-31', '2008-09-06', '2008-10-30', '20...","[461834, 369715, 386585, 284180, 96177, 383346]","['lemon vodka', 'cointreau liqueur', 'lemon ju...",183.2
155794,400756,5.000000,2,['toast'],ninja ham salad,1,23119,2009-11-23,3,"['2010-02-01', '2011-05-12']","[58104, 199848]","['onion', 'ham', 'mayonnaise', 'worcestershire...",231.1
106828,245164,3.750000,4,"['combine', 'microwave', 'toss']",scrumptious chocolate peanut butter cottage ch...,1,543029,2007-08-08,3,"['2008-01-05', '2008-02-27', '2009-08-08', '20...","[227652, 593726, 43083, 777453]","['cottage cheese', 'vanilla extract', 'peanut ...",109.8
133984,324128,5.000000,1,['pour'],something nutty,1,512309,2008-09-09,3,['2008-11-29'],[284180],"['kahlua', 'frangelico', 'milk', 'ice']",127.0

In [50]:
df = df[df["minutes"]<20000]
print(df.columns)
df = df.drop(columns=["contributor_id","user_id"])

Index(['recipe_id', 'mean_rating', 'comment_count', 'techniques', 'name',
       'minutes', 'contributor_id', 'submitted', 'n_steps', 'date', 'user_id',
       'ingredients_replaced', 'calories'],
      dtype='object')

In [51]:
df = df[["name","mean_rating","comment_count","submitted","minutes","ingredients_replaced","calories","techniques","n_steps","date","recipe_id"]].rename(columns={'mean_rating':'Note moyenne', 'comment_count':'Nombre de commentaires', 'name':'Nom',
       'submitted':'Date de publication de la recette', 'n_steps':"Nombre d'étapes", 'date':"Dates des commentaires", 'ingredients_replaced':"Ingrédients", "minutes":"Durée de la recette (minutes)", "calories":"Calories", "techniques":"Techniques utilisées"
       })

In [52]:
df.to_csv("../data/clean_cloud_df.csv")

In [53]:
df.columns

Index(['Nom', 'Note moyenne', 'Nombre de commentaires',
       'Date de publication de la recette', 'Durée de la recette',
       'Ingrédients', 'Calories', 'Techniques utilisées', 'Nombre d'étapes',
       'Dates des commentaires', 'recipe_id'],
      dtype='object')